#!/usr/bin/env bash

flags='--enable-features=UseOzonePlatform \
--ozone-platform=wayland \
--enable-features=WebRTCPipeWireCapturer \
--ignore-gpu-blacklist \
--enable-gpu-rasterization \
--enable-native-gpu-memory-buffers \
--enable-zero-copy \
--enable-accelerated-mjpeg-decode \
--enable-accelerated-video \
--use-gl=egl \
--disable-gpu-driver-bug-workarounds \
--enable-features=VaapiVideoDecoder \
--disable-software-rasterizer \
--start-maximized \
--js-flags="--max-old-space-size=5120"'

$1 $flags $2
