#!/usr/bin/env bash
flags='--enable-features=UseOzonePlatform --ozone-platform=wayland --enable-gpu \
--enable-features=WebRTCPipeWireCapturer \
--ignore-gpu-blocklist --enable-gpu-rasterization \
--disable-gpu-driver-bug-workarounds --enable-zero-copy \
--disable-software-rasterizer --start-maximized \
--js-flags="--max-old-space-size=5120"'
$1 $flags $2
