[style_color_symbol]
library_foreground = "Foreground"
library_background = "Reset"
library_border = "Blue"
library_highlight = "LightYellow"
library_highlight_symbol = "🦄"
playlist_foreground = "Foreground"
playlist_background = "Reset"
playlist_border = "Magenta"
playlist_highlight = "Red"
playlist_highlight_symbol = "🚀"
progress_foreground = "Blue"
progress_background = "Reset"
progress_border = "Cyan"
lyric_foreground = "Foreground"
lyric_background = "Reset"
lyric_border = "Green"

[style_color_symbol.alacritty_theme]
path = ""
name = "crag"
author = "Diego Aguilar"
background = "#1e1e2e"
foreground = "#cdd6f4"
cursor = "#f5e0dc"
text = "#45475a"
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"
light_black = "#a6adc8"
light_red = "#f38ba8"
light_green = "#a6e3a1"
light_yellow = "#f9e2af"
light_blue = "#89b4fa"
light_magenta = "#f5c2e7"
light_cyan = "#94e2d5"
light_white = "#ffffff"
