add_newline = false

[character]
# success_symbol = "[»](fg:#fee074)[»](fg:#f34f4d)[»](fg:#7ad88e)"
# vicmd_symbol = "[«](fg:#7ad88e)[«](fg:#f34f4d)[«](fg:#fee074)"
success_symbol = "[ﰉ](fg:#fb5c8e)[ ﰉ](fg:#f79f79)[ ﰉ](fg:#9fd3b3)"
vicmd_symbol = "[ﰊ](fg:#9fd3b3)[ ﰊ](fg:#f79f79)[ ﰊ](fg:#fb5c8e)"
error_symbol = "[ﰉ](fg:#fb5c8e)"

[git_metrics]
disabled = false

[directory.substitutions]
"~/Escritorio" = "  "
"~/Descargas" = "  "
"~/Documentos" = " "
"~/Imágenes" = " "
"~/Música" = " "
"~/Vídeos" = "  "
"~/Git" = " "
"/run/media/crag" = "禍 "

