add_newline = false

[character]
# success_symbol = "[»](fg:#fee074)[»](fg:#f34f4d)[»](fg:#7ad88e)"
# vicmd_symbol = "[«](fg:#7ad88e)[«](fg:#f34f4d)[«](fg:#fee074)"
success_symbol = "[ﰉ](fg:red)[ ﰉ](fg:yellow)[ ﰉ](fg:cyan)"
vicmd_symbol = "[ﰊ](fg:cyan)[ ﰊ](fg:yellow)[ ﰊ](fg:red)"
error_symbol = "[ﰉ](fg:red)"

[git_metrics]
disabled = false

[directory.substitutions]
"~/Escritorio" = "  "
"~/Descargas" = "  "
"~/Documentos" = " "
"~/Imágenes" = " "
"~/Música" = " "
"~/Vídeos" = "  "
"~/Git" = " "
"/run/media/crag" = "禍 "

